### ISSUE TITLE
Communications link failure

### ISSUE THREAD

**Issue by shooaaibb** [Bhanu1776/Java_Project#1]
Communications link failure last packet sent to the server was 0 ms ago. The driver hasn't received any packets from the server." I get this error whenever I try to register. Please help me out
![Screenshot (32)](https://user-images.githubusercontent.com/45943030/212547570-62d1e3ed-6f32-40eb-bbed-f5f312b2282d.png)

**Comment by Bhanu1776** [comment]
JDBC driver correctly installed on your device?
